export const PHRASES_7D = [
  'IT IS AWARE OF YOU',
  'SEVEN DAYS IS NOT MUCH',
  'TIME IS BLEEDING',
  'YOU ARE ALREADY LATE',
  'IT IS GETTING CLOSER',
  'EVERY SECOND COUNTS',
  'IT DOES NOT WAIT',
  'YOU CAN FEEL IT, CAN’T YOU?'
];

export const PHRASES_24H = [
  'FINAL DAY',
  'THERE IS NO MORE TIME',
  'IT IS HERE',
  'THE END IS LOCKED',
  'YOU WERE WARNED',
  'THIS IS THE LAST NIGHT',
  'DO NOT FALL ASLEEP',
  'IT KNOWS WHERE YOU ARE'
];
