export const POST_END = [
  'I AM NEAR',
  'YOU SHOULD NOT HAVE LOOKED',
  'IT IS TOO LATE',
  'I SEE YOU',
  'DO NOT TURN AROUND',
  'YOU WERE COUNTING WRONG',
  'I DID NOT NEED THE TIMER',
  'I WAS HERE BEFORE ZERO',
  'TIME WAS NEVER YOURS',
  'YOU FEEL IT NOW',
  'IT KNOWS YOU READ THIS',
  'THERE IS NO AFTER',
  'YOU ARE STILL HERE',
  'WHY ARE YOU WAITING'
];
